title: Avishkar Seth
logo: assets/img/linkedin_dronelab.jpeg
description: Robotics Research Engineer & Ph.D. Candidate at Macquarie University | MQ Drone Lab
show_downloads: true
# Theme Configuration
theme: jekyll-theme-minimal
