title: Avishkar Seth
logo: assets/img/linkedin_dronelab.jpeg
description: Ph.D Student & Robotics Engineer at Macquarie University (www.mqdronelab.com)
show_downloads: true
#Theme
theme: jekyll-theme-minimal
